paths:
  /api/v1/roles/{id}:
    delete:
      summary: Elimina un rol por su ID
      description: |
        Esta función elimina un rol por su ID utilizando el parámetro de ruta proporcionado.
      security:
        - bearerAuth: []
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          description: ID del rol a eliminar
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Rol eliminado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error
      securityDefinitions:
        bearerAuth:
          type: apiKey
          name: Authorization
          in: header