paths:
  /api/v1/roles/{id}:
    put:
      summary: Actualiza un rol por su ID
      description: |
        Esta función actualiza un rol por su ID utilizando el parámetro de ruta proporcionado y los datos proporcionados en el cuerpo de la solicitud.
      security:
        - bearerAuth: []
      tags:
        - Roles
      parameters:
        - in: path
          name: id
          description: ID del rol a actualizar
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nuevo nombre del rol
                state:
                  type: boolean
                  description: Nuevo estado del rol
            example:
              name: "Prueba de actualización"
              state: true
      responses:
        '200':
          description: Rol actualizado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
        '400':
          description: Error de solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de error
      securityDefinitions:
        bearerAuth:
          type: apiKey
          name: Authorization
          in: header